/**
 * Leaderboard Hook
 * Fetches leaderboard data using React Query
 */

'use client';

import { useQuery } from '@tanstack/react-query';
import { getLeaderboard, LeaderboardParams, LeaderboardResponse } from '../lib/api/leaderboard';
import { getBoxImageUrl } from '../lib/utils/boxImages';

// Mock data - only used when NEXT_PUBLIC_USE_MOCK_DATA=true is set
// Default behavior: API failures will show error state, not mock data
const MOCK_DATA: LeaderboardResponse = {
  data: [
    {
      id: '1',
      rank: 1,
      rank_change_direction: 'up',
      rank_change_amount: 2,
      product_name: 'One Piece - OP-02 Paramount War Booster Box',
      set_name: 'Paramount War',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-02 Paramount War Booster Box'),
      metrics: {
        floor_price_usd: 285.50,
        floor_price_1d_change_pct: 5.2,
        daily_volume_usd: 125000,
        unified_volume_7d_ema: 850000,
        units_sold_count: 45,
        active_listings_count: 120,
        listed_percentage: 12.5,
        estimated_total_supply: 10000,
        liquidity_score: 8.7,
        days_to_20pct_increase: 14,
        expected_days_to_sell: 8,
        price_sparkline_1d: [270, 275, 280, 278, 282, 285, 285.5],
      },
      reprint_risk: 'LOW',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '2',
      rank: 2,
      rank_change_direction: 'same',
      rank_change_amount: 0,
      product_name: 'One Piece - OP-03 Pillars of Strength Booster Box',
      set_name: 'Pillars of Strength',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-03 Pillars of Strength Booster Box'),
      metrics: {
        floor_price_usd: 245.00,
        floor_price_1d_change_pct: 2.1,
        daily_volume_usd: 98000,
        unified_volume_7d_ema: 720000,
        units_sold_count: 38,
        active_listings_count: 95,
        listed_percentage: 15.2,
        estimated_total_supply: 8500,
        liquidity_score: 8.2,
        days_to_20pct_increase: 18,
        expected_days_to_sell: 10,
        price_sparkline_1d: [240, 242, 243, 244, 245, 244, 245],
      },
      reprint_risk: 'LOW',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '3',
      rank: 3,
      rank_change_direction: 'down',
      rank_change_amount: 1,
      product_name: 'One Piece - OP-01 Romance Dawn Booster Box (Blue)',
      set_name: 'Romance Dawn',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-01 Romance Dawn Booster Box (Blue)'),
      metrics: {
        floor_price_usd: 320.00,
        floor_price_1d_change_pct: -1.5,
        daily_volume_usd: 85000,
        unified_volume_7d_ema: 680000,
        units_sold_count: 32,
        active_listings_count: 110,
        listed_percentage: 18.5,
        estimated_total_supply: 12000,
        liquidity_score: 7.9,
        days_to_20pct_increase: 22,
        expected_days_to_sell: 12,
        price_sparkline_1d: [325, 323, 322, 321, 320, 319, 320],
      },
      reprint_risk: 'MEDIUM',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '4',
      rank: 4,
      rank_change_direction: 'up',
      rank_change_amount: 3,
      product_name: 'One Piece - OP-04 Kingdoms of Intrigue Booster Box',
      set_name: 'Kingdoms of Intrigue',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-04 Kingdoms of Intrigue Booster Box'),
      metrics: {
        floor_price_usd: 195.00,
        floor_price_1d_change_pct: 8.3,
        daily_volume_usd: 72000,
        unified_volume_7d_ema: 550000,
        units_sold_count: 28,
        active_listings_count: 85,
        listed_percentage: 14.8,
        estimated_total_supply: 9000,
        liquidity_score: 7.5,
        days_to_20pct_increase: 16,
        expected_days_to_sell: 9,
        price_sparkline_1d: [180, 185, 190, 192, 193, 194, 195],
      },
      reprint_risk: 'LOW',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '5',
      rank: 5,
      rank_change_direction: 'same',
      rank_change_amount: 0,
      product_name: 'One Piece - OP-05 Awakening of the New Era Booster Box',
      set_name: 'Awakening of the New Era',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-05 Awakening of the New Era Booster Box'),
      metrics: {
        floor_price_usd: 175.00,
        floor_price_1d_change_pct: 1.2,
        daily_volume_usd: 65000,
        unified_volume_7d_ema: 480000,
        units_sold_count: 25,
        active_listings_count: 75,
        listed_percentage: 16.3,
        estimated_total_supply: 8000,
        liquidity_score: 7.2,
        days_to_20pct_increase: 20,
        expected_days_to_sell: 11,
        price_sparkline_1d: [173, 174, 174.5, 175, 174, 175, 175],
      },
      reprint_risk: 'LOW',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '6',
      rank: 6,
      rank_change_direction: 'down',
      rank_change_amount: 2,
      product_name: 'One Piece - OP-01 Romance Dawn Booster Box (White)',
      set_name: 'Romance Dawn',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-01 Romance Dawn Booster Box (White)'),
      metrics: {
        floor_price_usd: 310.00,
        floor_price_1d_change_pct: -2.8,
        daily_volume_usd: 58000,
        unified_volume_7d_ema: 420000,
        units_sold_count: 22,
        active_listings_count: 95,
        listed_percentage: 19.2,
        estimated_total_supply: 11000,
        liquidity_score: 6.8,
        days_to_20pct_increase: 25,
        expected_days_to_sell: 14,
        price_sparkline_1d: [318, 315, 313, 312, 311, 310, 310],
      },
      reprint_risk: 'MEDIUM',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '7',
      rank: 7,
      rank_change_direction: 'up',
      rank_change_amount: 1,
      product_name: 'One Piece - OP-06 Wings of the Captain Booster Box',
      set_name: 'Wings of the Captain',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-06 Wings of the Captain Booster Box'),
      metrics: {
        floor_price_usd: 155.00,
        floor_price_1d_change_pct: 4.5,
        daily_volume_usd: 52000,
        unified_volume_7d_ema: 380000,
        units_sold_count: 20,
        active_listings_count: 68,
        listed_percentage: 15.7,
        estimated_total_supply: 7500,
        liquidity_score: 6.5,
        days_to_20pct_increase: 18,
        expected_days_to_sell: 10,
        price_sparkline_1d: [148, 150, 152, 153, 154, 155, 155],
      },
      reprint_risk: 'LOW',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '8',
      rank: 8,
      rank_change_direction: 'same',
      rank_change_amount: 0,
      product_name: 'One Piece - OP-07 500 Years In The Future Booster Box',
      set_name: '500 Years In The Future',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-07 500 Years In The Future Booster Box'),
      metrics: {
        floor_price_usd: 140.00,
        floor_price_1d_change_pct: 0.8,
        daily_volume_usd: 48000,
        unified_volume_7d_ema: 350000,
        units_sold_count: 18,
        active_listings_count: 62,
        listed_percentage: 17.1,
        estimated_total_supply: 7000,
        liquidity_score: 6.2,
        days_to_20pct_increase: 22,
        expected_days_to_sell: 12,
        price_sparkline_1d: [139, 139.5, 140, 140, 139.5, 140, 140],
      },
      reprint_risk: 'LOW',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '9',
      rank: 9,
      rank_change_direction: 'up',
      rank_change_amount: 4,
      product_name: 'One Piece - OP-08 Two Legends Booster Box',
      set_name: 'Two Legends',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-08 Two Legends Booster Box'),
      metrics: {
        floor_price_usd: 125.00,
        floor_price_1d_change_pct: 6.2,
        daily_volume_usd: 42000,
        unified_volume_7d_ema: 310000,
        units_sold_count: 16,
        active_listings_count: 55,
        listed_percentage: 16.5,
        estimated_total_supply: 6500,
        liquidity_score: 5.9,
        days_to_20pct_increase: 20,
        expected_days_to_sell: 11,
        price_sparkline_1d: [118, 120, 122, 123, 124, 125, 125],
      },
      reprint_risk: 'LOW',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '10',
      rank: 10,
      rank_change_direction: 'down',
      rank_change_amount: 1,
      product_name: 'One Piece - OP-09 Emperors of the New World Booster Box',
      set_name: 'Emperors of the New World',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-09 Emperors of the New World Booster Box'),
      metrics: {
        floor_price_usd: 115.00,
        floor_price_1d_change_pct: -1.2,
        daily_volume_usd: 38000,
        unified_volume_7d_ema: 280000,
        units_sold_count: 15,
        active_listings_count: 50,
        listed_percentage: 18.3,
        estimated_total_supply: 6000,
        liquidity_score: 5.6,
        days_to_20pct_increase: 24,
        expected_days_to_sell: 13,
        price_sparkline_1d: [116, 115.5, 115, 115.5, 115, 114.5, 115],
      },
      reprint_risk: 'MEDIUM',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '11',
      rank: 11,
      rank_change_direction: 'same',
      rank_change_amount: 0,
      product_name: 'One Piece - OP-10 Royal Blood Booster Box',
      set_name: 'Royal Blood',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-10 Royal Blood Booster Box'),
      metrics: {
        floor_price_usd: 105.00,
        floor_price_1d_change_pct: 2.3,
        daily_volume_usd: 35000,
        unified_volume_7d_ema: 250000,
        units_sold_count: 14,
        active_listings_count: 48,
        listed_percentage: 17.8,
        estimated_total_supply: 5800,
        liquidity_score: 5.3,
        days_to_20pct_increase: 26,
        expected_days_to_sell: 14,
        price_sparkline_1d: [102, 103, 104, 104.5, 105, 105, 105],
      },
      reprint_risk: 'MEDIUM',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '12',
      rank: 12,
      rank_change_direction: 'up',
      rank_change_amount: 2,
      product_name: 'One Piece - OP-11 A Fist of Divine Speed Booster Box',
      set_name: 'A Fist of Divine Speed',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-11 A Fist of Divine Speed Booster Box'),
      metrics: {
        floor_price_usd: 95.00,
        floor_price_1d_change_pct: 3.7,
        daily_volume_usd: 32000,
        unified_volume_7d_ema: 220000,
        units_sold_count: 12,
        active_listings_count: 42,
        listed_percentage: 19.1,
        estimated_total_supply: 5500,
        liquidity_score: 5.0,
        days_to_20pct_increase: 28,
        expected_days_to_sell: 15,
        price_sparkline_1d: [92, 93, 94, 94.5, 95, 95, 95],
      },
      reprint_risk: 'MEDIUM',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '13',
      rank: 13,
      rank_change_direction: 'same',
      rank_change_amount: 0,
      product_name: 'One Piece - OP-12 Legacy of the Master Booster Box',
      set_name: 'Legacy of the Master',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-12 Legacy of the Master Booster Box'),
      metrics: {
        floor_price_usd: 85.00,
        floor_price_1d_change_pct: 1.5,
        daily_volume_usd: 28000,
        unified_volume_7d_ema: 190000,
        units_sold_count: 11,
        active_listings_count: 38,
        listed_percentage: 18.6,
        estimated_total_supply: 5000,
        liquidity_score: 4.7,
        days_to_20pct_increase: 30,
        expected_days_to_sell: 16,
        price_sparkline_1d: [84, 84.5, 85, 85, 84.5, 85, 85],
      },
      reprint_risk: 'HIGH',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '14',
      rank: 14,
      rank_change_direction: 'down',
      rank_change_amount: 3,
      product_name: 'One Piece - OP-13 Carrying on His Will Booster Box',
      set_name: 'Carrying on His Will',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-13 Carrying on His Will Booster Box'),
      metrics: {
        floor_price_usd: 75.00,
        floor_price_1d_change_pct: -3.2,
        daily_volume_usd: 25000,
        unified_volume_7d_ema: 165000,
        units_sold_count: 10,
        active_listings_count: 35,
        listed_percentage: 20.2,
        estimated_total_supply: 4800,
        liquidity_score: 4.4,
        days_to_20pct_increase: 32,
        expected_days_to_sell: 18,
        price_sparkline_1d: [78, 77, 76, 75.5, 75, 74.5, 75],
      },
      reprint_risk: 'HIGH',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '15',
      rank: 15,
      rank_change_direction: 'up',
      rank_change_amount: 1,
      product_name: 'One Piece - EB-01 Memorial Collection Booster Box',
      set_name: 'Memorial Collection',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - EB-01 Memorial Collection Booster Box'),
      metrics: {
        floor_price_usd: 165.00,
        floor_price_1d_change_pct: 7.8,
        daily_volume_usd: 22000,
        unified_volume_7d_ema: 140000,
        units_sold_count: 9,
        active_listings_count: 32,
        listed_percentage: 21.5,
        estimated_total_supply: 4500,
        liquidity_score: 4.1,
        days_to_20pct_increase: 35,
        expected_days_to_sell: 19,
        price_sparkline_1d: [153, 156, 159, 161, 163, 164, 165],
      },
      reprint_risk: 'LOW',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '16',
      rank: 16,
      rank_change_direction: 'same',
      rank_change_amount: 0,
      product_name: 'One Piece - EB-02 Anime 25th Collection Booster Box',
      set_name: 'Anime 25th Collection',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - EB-02 Anime 25th Collection Booster Box'),
      metrics: {
        floor_price_usd: 145.00,
        floor_price_1d_change_pct: 0.5,
        daily_volume_usd: 18000,
        unified_volume_7d_ema: 120000,
        units_sold_count: 8,
        active_listings_count: 28,
        listed_percentage: 22.1,
        estimated_total_supply: 4200,
        liquidity_score: 3.8,
        days_to_20pct_increase: 38,
        expected_days_to_sell: 20,
        price_sparkline_1d: [144, 144.5, 145, 145, 144.5, 145, 145],
      },
      reprint_risk: 'LOW',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '17',
      rank: 17,
      rank_change_direction: 'up',
      rank_change_amount: 2,
      product_name: 'One Piece - PRB-01 Premium Booster Box (The Best)',
      set_name: 'Premium Booster Box (The Best)',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - PRB-01 Premium Booster Box (The Best)'),
      metrics: {
        floor_price_usd: 220.00,
        floor_price_1d_change_pct: 4.2,
        daily_volume_usd: 15000,
        unified_volume_7d_ema: 95000,
        units_sold_count: 7,
        active_listings_count: 25,
        listed_percentage: 23.8,
        estimated_total_supply: 3800,
        liquidity_score: 3.5,
        days_to_20pct_increase: 40,
        expected_days_to_sell: 22,
        price_sparkline_1d: [211, 214, 217, 218, 219, 220, 220],
      },
      reprint_risk: 'LOW',
      metric_date: new Date().toISOString().split('T')[0],
    },
  ],
  meta: {
    total: 17,
    sort: 'unified_volume_7d_ema',
    sort_direction: 'desc',
    limit: 100,
    offset: 0,
  },
};

export function useLeaderboard(params: LeaderboardParams = {}) {
  return useQuery<LeaderboardResponse>({
    queryKey: ['leaderboard', params],
    queryFn: async () => {
      // Always call the real API - no mock fallback
      // 401 errors will be handled in getLeaderboard and redirect to login
      const result = await getLeaderboard(params);
      return result;
    },
    staleTime: 5 * 60 * 1000, // 5 minutes - show cached data immediately, refetch in background
    refetchOnWindowFocus: false,
    retry: false, // Don't retry on 401 errors (will redirect instead)
    retryOnMount: true,
    refetchOnReconnect: true,
    refetchOnMount: true,
  });
}
