/**
 * Leaderboard Hook
 * Fetches leaderboard data using React Query
 */

'use client';

import { useQuery } from '@tanstack/react-query';
import { getLeaderboard, LeaderboardParams, LeaderboardResponse } from '../lib/api/leaderboard';
import { getBoxImageUrl } from '../lib/utils/boxImages';

// Mock data - only used when NEXT_PUBLIC_USE_MOCK_DATA=true is set
// Default behavior: API failures will show error state, not mock data
const MOCK_DATA: LeaderboardResponse = {
  data: [
    {
      id: '1',
      rank: 1,
      rank_change_direction: 'up',
      rank_change_amount: 2,
      product_name: 'One Piece - OP-02 Paramount War Booster Box',
      set_name: 'Paramount War',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-02 Paramount War Booster Box'),
      metrics: {
        floor_price_usd: 285.50,
        floor_price_1d_change_pct: 5.2,
        daily_volume_usd: 125000,
        unified_volume_7d_ema: 850000,
        units_sold_count: 45,
        active_listings_count: 120,
        liquidity_score: 8.7,
        days_to_20pct_increase: 14,
        expected_days_to_sell: 8,
      },
      reprint_risk: 'LOW',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '2',
      rank: 2,
      rank_change_direction: 'same',
      rank_change_amount: 0,
      product_name: 'One Piece - OP-03 Pillars of Strength Booster Box',
      set_name: 'Pillars of Strength',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-03 Pillars of Strength Booster Box'),
      metrics: {
        floor_price_usd: 245.00,
        floor_price_1d_change_pct: 2.1,
        daily_volume_usd: 98000,
        unified_volume_7d_ema: 720000,
        units_sold_count: 38,
        active_listings_count: 95,
        liquidity_score: 8.2,
        days_to_20pct_increase: 18,
        expected_days_to_sell: 10,
      },
      reprint_risk: 'LOW',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '3',
      rank: 3,
      rank_change_direction: 'down',
      rank_change_amount: 1,
      product_name: 'One Piece - OP-01 Romance Dawn Booster Box (Blue)',
      set_name: 'Romance Dawn',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-01 Romance Dawn Booster Box (Blue)'),
      metrics: {
        floor_price_usd: 320.00,
        floor_price_1d_change_pct: -1.5,
        daily_volume_usd: 85000,
        unified_volume_7d_ema: 680000,
        units_sold_count: 32,
        active_listings_count: 110,
        liquidity_score: 7.9,
        days_to_20pct_increase: 22,
        expected_days_to_sell: 12,
      },
      reprint_risk: 'MEDIUM',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '4',
      rank: 4,
      rank_change_direction: 'up',
      rank_change_amount: 3,
      product_name: 'One Piece - OP-04 Kingdoms of Intrigue Booster Box',
      set_name: 'Kingdoms of Intrigue',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-04 Kingdoms of Intrigue Booster Box'),
      metrics: {
        floor_price_usd: 195.00,
        floor_price_1d_change_pct: 8.3,
        daily_volume_usd: 72000,
        unified_volume_7d_ema: 550000,
        units_sold_count: 28,
        active_listings_count: 85,
        liquidity_score: 7.5,
        days_to_20pct_increase: 16,
        expected_days_to_sell: 9,
      },
      reprint_risk: 'LOW',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '5',
      rank: 5,
      rank_change_direction: 'same',
      rank_change_amount: 0,
      product_name: 'One Piece - OP-05 Awakening of the New Era Booster Box',
      set_name: 'Awakening of the New Era',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-05 Awakening of the New Era Booster Box'),
      metrics: {
        floor_price_usd: 175.00,
        floor_price_1d_change_pct: 1.2,
        daily_volume_usd: 65000,
        unified_volume_7d_ema: 480000,
        units_sold_count: 25,
        active_listings_count: 75,
        liquidity_score: 7.2,
        days_to_20pct_increase: 20,
        expected_days_to_sell: 11,
      },
      reprint_risk: 'LOW',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '6',
      rank: 6,
      rank_change_direction: 'down',
      rank_change_amount: 2,
      product_name: 'One Piece - OP-01 Romance Dawn Booster Box (White)',
      set_name: 'Romance Dawn',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-01 Romance Dawn Booster Box (White)'),
      metrics: {
        floor_price_usd: 310.00,
        floor_price_1d_change_pct: -2.8,
        daily_volume_usd: 58000,
        unified_volume_7d_ema: 420000,
        units_sold_count: 22,
        active_listings_count: 95,
        liquidity_score: 6.8,
        days_to_20pct_increase: 25,
        expected_days_to_sell: 14,
      },
      reprint_risk: 'MEDIUM',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '7',
      rank: 7,
      rank_change_direction: 'up',
      rank_change_amount: 1,
      product_name: 'One Piece - OP-06 Wings of the Captain Booster Box',
      set_name: 'Wings of the Captain',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-06 Wings of the Captain Booster Box'),
      metrics: {
        floor_price_usd: 155.00,
        floor_price_1d_change_pct: 4.5,
        daily_volume_usd: 52000,
        unified_volume_7d_ema: 380000,
        units_sold_count: 20,
        active_listings_count: 68,
        liquidity_score: 6.5,
        days_to_20pct_increase: 18,
        expected_days_to_sell: 10,
      },
      reprint_risk: 'LOW',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '8',
      rank: 8,
      rank_change_direction: 'same',
      rank_change_amount: 0,
      product_name: 'One Piece - OP-07 500 Years In The Future Booster Box',
      set_name: '500 Years In The Future',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-07 500 Years In The Future Booster Box'),
      metrics: {
        floor_price_usd: 140.00,
        floor_price_1d_change_pct: 0.8,
        daily_volume_usd: 48000,
        unified_volume_7d_ema: 350000,
        units_sold_count: 18,
        active_listings_count: 62,
        liquidity_score: 6.2,
        days_to_20pct_increase: 22,
        expected_days_to_sell: 12,
      },
      reprint_risk: 'LOW',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '9',
      rank: 9,
      rank_change_direction: 'up',
      rank_change_amount: 4,
      product_name: 'One Piece - OP-08 Two Legends Booster Box',
      set_name: 'Two Legends',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-08 Two Legends Booster Box'),
      metrics: {
        floor_price_usd: 125.00,
        floor_price_1d_change_pct: 6.2,
        daily_volume_usd: 42000,
        unified_volume_7d_ema: 310000,
        units_sold_count: 16,
        active_listings_count: 55,
        liquidity_score: 5.9,
        days_to_20pct_increase: 20,
        expected_days_to_sell: 11,
      },
      reprint_risk: 'LOW',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '10',
      rank: 10,
      rank_change_direction: 'down',
      rank_change_amount: 1,
      product_name: 'One Piece - OP-09 Emperors in the New World Booster Box',
      set_name: 'Emperors in the New World',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-09 Emperors in the New World Booster Box'),
      metrics: {
        floor_price_usd: 115.00,
        floor_price_1d_change_pct: -1.2,
        daily_volume_usd: 38000,
        unified_volume_7d_ema: 280000,
        units_sold_count: 15,
        active_listings_count: 50,
        liquidity_score: 5.6,
        days_to_20pct_increase: 24,
        expected_days_to_sell: 13,
      },
      reprint_risk: 'MEDIUM',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '11',
      rank: 11,
      rank_change_direction: 'same',
      rank_change_amount: 0,
      product_name: 'One Piece - OP-10 Royal Blood Booster Box',
      set_name: 'Royal Blood',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-10 Royal Blood Booster Box'),
      metrics: {
        floor_price_usd: 105.00,
        floor_price_1d_change_pct: 2.3,
        daily_volume_usd: 35000,
        unified_volume_7d_ema: 250000,
        units_sold_count: 14,
        active_listings_count: 48,
        liquidity_score: 5.3,
        days_to_20pct_increase: 26,
        expected_days_to_sell: 14,
      },
      reprint_risk: 'MEDIUM',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '12',
      rank: 12,
      rank_change_direction: 'up',
      rank_change_amount: 2,
      product_name: 'One Piece - OP-11 A Fist of Divine Speed Booster Box',
      set_name: 'A Fist of Divine Speed',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-11 A Fist of Divine Speed Booster Box'),
      metrics: {
        floor_price_usd: 95.00,
        floor_price_1d_change_pct: 3.7,
        daily_volume_usd: 32000,
        unified_volume_7d_ema: 220000,
        units_sold_count: 12,
        active_listings_count: 42,
        liquidity_score: 5.0,
        days_to_20pct_increase: 28,
        expected_days_to_sell: 15,
      },
      reprint_risk: 'MEDIUM',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '13',
      rank: 13,
      rank_change_direction: 'same',
      rank_change_amount: 0,
      product_name: 'One Piece - OP-12 Legacy of the Master Booster Box',
      set_name: 'Legacy of the Master',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-12 Legacy of the Master Booster Box'),
      metrics: {
        floor_price_usd: 85.00,
        floor_price_1d_change_pct: 1.5,
        daily_volume_usd: 28000,
        unified_volume_7d_ema: 190000,
        units_sold_count: 11,
        active_listings_count: 38,
        liquidity_score: 4.7,
        days_to_20pct_increase: 30,
        expected_days_to_sell: 16,
      },
      reprint_risk: 'HIGH',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '14',
      rank: 14,
      rank_change_direction: 'down',
      rank_change_amount: 3,
      product_name: 'One Piece - OP-13 Carrying on His Will Booster Box',
      set_name: 'Carrying on His Will',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - OP-13 Carrying on His Will Booster Box'),
      metrics: {
        floor_price_usd: 75.00,
        floor_price_1d_change_pct: -3.2,
        daily_volume_usd: 25000,
        unified_volume_7d_ema: 165000,
        units_sold_count: 10,
        active_listings_count: 35,
        liquidity_score: 4.4,
        days_to_20pct_increase: 32,
        expected_days_to_sell: 18,
      },
      reprint_risk: 'HIGH',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '15',
      rank: 15,
      rank_change_direction: 'up',
      rank_change_amount: 1,
      product_name: 'One Piece - EB-01 Memorial Collection Booster Box',
      set_name: 'Memorial Collection',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - EB-01 Memorial Collection Booster Box'),
      metrics: {
        floor_price_usd: 165.00,
        floor_price_1d_change_pct: 7.8,
        daily_volume_usd: 22000,
        unified_volume_7d_ema: 140000,
        units_sold_count: 9,
        active_listings_count: 32,
        liquidity_score: 4.1,
        days_to_20pct_increase: 35,
        expected_days_to_sell: 19,
      },
      reprint_risk: 'LOW',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '16',
      rank: 16,
      rank_change_direction: 'same',
      rank_change_amount: 0,
      product_name: 'One Piece - EB-02 Anime 25th Collection Booster Box',
      set_name: 'Anime 25th Collection',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - EB-02 Anime 25th Collection Booster Box'),
      metrics: {
        floor_price_usd: 145.00,
        floor_price_1d_change_pct: 0.5,
        daily_volume_usd: 18000,
        unified_volume_7d_ema: 120000,
        units_sold_count: 8,
        active_listings_count: 28,
        liquidity_score: 3.8,
        days_to_20pct_increase: 38,
        expected_days_to_sell: 20,
      },
      reprint_risk: 'LOW',
      metric_date: new Date().toISOString().split('T')[0],
    },
    {
      id: '17',
      rank: 17,
      rank_change_direction: 'up',
      rank_change_amount: 2,
      product_name: 'One Piece - PRB-01 Premium Booster Box (The Best)',
      set_name: 'Premium Booster Box (The Best)',
      game_type: 'One Piece',
      image_url: getBoxImageUrl('One Piece - PRB-01 Premium Booster Box (The Best)'),
      metrics: {
        floor_price_usd: 220.00,
        floor_price_1d_change_pct: 4.2,
        daily_volume_usd: 15000,
        unified_volume_7d_ema: 95000,
        units_sold_count: 7,
        active_listings_count: 25,
        liquidity_score: 3.5,
        days_to_20pct_increase: 40,
        expected_days_to_sell: 22,
      },
      reprint_risk: 'LOW',
      metric_date: new Date().toISOString().split('T')[0],
    },
  ],
  meta: {
    total: 17,
    sort: 'unified_volume_7d_ema',
    sort_direction: 'desc',
    limit: 100,
    offset: 0,
  },
};

const commonOpts = {
  staleTime: 5 * 60 * 1000,
  refetchOnWindowFocus: false,
  retry: false,
  retryOnMount: true,
  refetchOnReconnect: true,
  refetchOnMount: true,
};

export function useLeaderboard(params: LeaderboardParams & { fastLimit?: number; fullLimit?: number } = {}) {
  const { fastLimit, fullLimit, ...rest } = params;
  const useTwoPhase = fastLimit != null && fullLimit != null;
  const fastLimitVal = useTwoPhase ? fastLimit! : (rest.limit ?? 100);
  const fullLimitVal = useTwoPhase ? fullLimit! : fastLimitVal;

  const fastQuery = useQuery<LeaderboardResponse>({
    queryKey: ['leaderboard', { ...rest, limit: fastLimitVal }],
    queryFn: () => getLeaderboard({ ...rest, limit: fastLimitVal }),
    ...commonOpts,
  });

  const fullQuery = useQuery<LeaderboardResponse>({
    queryKey: ['leaderboard', { ...rest, limit: fullLimitVal }],
    queryFn: () => getLeaderboard({ ...rest, limit: fullLimitVal }),
    ...commonOpts,
    enabled: useTwoPhase ? !!fastQuery.data : false,
  });

  if (useTwoPhase) {
    const data = fullQuery.data ?? fastQuery.data;
    const isLoading = fastQuery.isLoading;
    const isFetchingMore = fullQuery.isFetching && !!fastQuery.data;
    return {
      data,
      isLoading,
      isFetchingMore,
      error: fastQuery.error ?? fullQuery.error,
      isError: fastQuery.isError || fullQuery.isError,
      refetch: () => {
        fastQuery.refetch();
        fullQuery.refetch();
      },
      isRefetching: fastQuery.isRefetching || fullQuery.isRefetching,
      status: fastQuery.status,
      fetchStatus: fullQuery.data ? fullQuery.fetchStatus : fastQuery.fetchStatus,
    } as ReturnType<typeof useQuery<LeaderboardResponse>> & { isFetchingMore?: boolean };
  }

  return { ...fastQuery, isFetchingMore: false };
}
